What is Encoding?
---

Encoding is the process of converting categorical data (text values) into a numerical format so that Machine Learning algorithms can understand and process it.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("used_car_dataset.csv")

In [3]:
df

,year,mileage,fuel_type,transmission,seller_type,car_condition,brand,price
0,2006,158812,Electric,Automatic,Dealer,Excellent,BMW,15636
1,2019,64353,Diesel,Manual,Dealer,Poor,Toyota,6583
2,2014,118132,Diesel,Manual,Dealer,Excellent,Toyota,10821
3,2010,192604,Electric,Automatic,Dealer,Excellent,Tesla,15681
4,2007,21052,Diesel,Automatic,Dealer,Good,Hyundai,11798
...,...,...,...,...,...,...,...,...
2495,2022,119589,Electric,Manual,Individual,Good,Toyota,10008
2496,2006,150406,Diesel,Automatic,Online Platform,Good,Ford,9153
2497,2004,99715,Electric,Semi-Auto,Individual,Excellent,Hyundai,9644
2498,2000,198839,Hybrid,Semi-Auto,Individual,Fair,Ford,5369
2499,2012,11644,Diesel,Manual,Online Platform,Poor,Hyundai,6466

Ordinal Encoding
----
What is Ordinal Data?

Ordinal data is categorical data where the categories have a meaningful order or ranking.


When to Use Ordinal Encoding?
--
Use Ordinal Encoding when categorical values have a meaningful order or ranking.

Examples:
--
Low < Medium < High

Poor < Average < Good < Excellent

Beginner < Intermediate < Advanced

Bronze < Silver < Gold < Platinum

In [4]:
df['car_condition'].unique()

<ArrowStringArray>
['Excellent', 'Poor', 'Good', 'Fair']
Length: 4, dtype: str

In [5]:
df['year_binned'] = pd.cut(df['year'], bins=3, labels=['Old', 'Mid', 'New'])

In [6]:
df['year_binned'].unique()

['Old', 'New', 'Mid']
Categories (3, str): ['Old' < 'Mid' < 'New']

In [7]:
transmission_order = [['Manual', 'Semi-Auto', 'Automatic']]#1,2,3
condition_order = [['Poor', 'Fair', 'Good', 'Excellent']]#1,2,3,4

In [8]:
trans_encoder = OrdinalEncoder(categories=transmission_order)
df['transmission_encoded'] = trans_encoder.fit_transform(df[['transmission']])

cond_encoder = OrdinalEncoder(categories=condition_order)
df['car_condition_encoded'] = cond_encoder.fit_transform(df[['car_condition']])

In [9]:
df['car_condition_encoded'].unique(),df['car_condition'].unique()

(array([3., 0., 2., 1.]),
 <ArrowStringArray>
 ['Excellent', 'Poor', 'Good', 'Fair']
 Length: 4, dtype: str)

In [10]:
df[['transmission_encoded','transmission']]

      transmission_encoded transmission
0                      2.0    Automatic
1                      0.0       Manual
2                      0.0       Manual
3                      2.0    Automatic
4                      2.0    Automatic
...                    ...          ...
2495                   0.0       Manual
2496                   2.0    Automatic
2497                   1.0    Semi-Auto
2498                   1.0    Semi-Auto
2499                   0.0       Manual

[2500 rows x 2 columns]

In [11]:
brand_means = df.groupby('brand')['price'].mean()
df['brand_encoded'] = df['brand'].map(brand_means)

In [15]:
df['fuel_type']

0       Electric
1         Diesel
2         Diesel
3       Electric
4         Diesel
          ...
2495    Electric
2496      Diesel
2497    Electric
2498      Hybrid
2499      Diesel
Name: fuel_type, Length: 2500, dtype: str

In [23]:
fule_type=df['fuel_type'].to_numpy().reshape(-1, 1)

One-Hot Encoding
---
What is Nominal Data?

Nominal data is categorical data where there is no meaningful order or ranking.

Example
--

Original Data:

City
Pune
Mumbai
Delhi

In [36]:
encoder = OneHotEncoder(sparse_output=True)

encoded_data = encoder.fit_transform(df[['fuel_type']])

encoded_df = pd.DataFrame(
    encoded_data.toarray(),
    columns=encoder.get_feature_names_out(['fuel_type']),
    index=df.index
)

encoded_df.head()

   fuel_type_Diesel  fuel_type_Electric  fuel_type_Hybrid  fuel_type_Petrol
0               0.0                 1.0               0.0               0.0
1               1.0                 0.0               0.0               0.0
2               1.0                 0.0               0.0               0.0
3               0.0                 1.0               0.0               0.0
4               1.0                 0.0               0.0               0.0